title: Azure-411
description: Get your Azure Learn on!
theme: just-the-docs

# url: https://just-the-docs.github.io
url: "https://rickcau.github.io"
baseurl: "/Azure-411"

aux_links:
  Youtube: https://github.com/just-the-docs/just-the-docs-template
  Logic App Repo: https://github.com/Rickcau/LogicApps
  
  
include:
  - _assets
